name: check-bun-wasm-rust-dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: read
  pull-requests: write
jobs:
  call-check-bun-dependencies:
    uses: flowscripter/.github/.github/workflows/check-bun-wasm-rust-dependencies.yml@v1
    secrets: inherit
